-- Inserts opcionais para registar documentos simulados no MEDICORE
-- Copiar previamente os ficheiros para private/assets/documentos/

INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '01.001' LIMIT 1), 'contrato_aquisicao', 'Contrato de Aquisicao - Ventilador Pulmonar', 'equipamentos/01.001/contratos/contrato_aquisicao_01_001_ventilador_pulmonar.pdf', '2022-03-01', NULL, 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '02.001' LIMIT 1), 'contrato_aquisicao', 'Contrato de Aquisicao - Ecografo Portatil', 'equipamentos/02.001/contratos/contrato_aquisicao_02_001_ecografo_portatil.pdf', '2021-08-20', NULL, 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '05.001' LIMIT 1), 'contrato_aquisicao', 'Contrato de Aquisicao - Bomba Infusora Volumetrica', 'equipamentos/05.001/contratos/contrato_aquisicao_05_001_bomba_infusora_volumetrica.pdf', '2023-03-01', NULL, 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '07.001' LIMIT 1), 'contrato_aquisicao', 'Contrato de Aquisicao - Incubadora Neonatal', 'equipamentos/07.001/contratos/contrato_aquisicao_07_001_incubadora_neonatal.pdf', '2022-01-10', NULL, 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '01.001' LIMIT 1), 'contrato_garantia', 'Contrato de Garantia - Ventilador Pulmonar', 'equipamentos/01.001/garantias/contrato_garantia_01_001_ventilador_pulmonar.pdf', '2022-03-15', '2025-03-15', 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '04.001' LIMIT 1), 'contrato_garantia', 'Contrato de Garantia - Monitor Multiparametrico', 'equipamentos/04.001/garantias/contrato_garantia_04_001_monitor_multiparametrico.pdf', '2022-08-20', '2025-08-20', 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '05.001' LIMIT 1), 'contrato_garantia', 'Contrato de Garantia - Bomba Infusora Volumetrica', 'equipamentos/05.001/garantias/contrato_garantia_05_001_bomba_infusora_volumetrica.pdf', '2023-03-10', '2026-03-10', 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '07.001' LIMIT 1), 'contrato_garantia', 'Contrato de Garantia - Incubadora Neonatal', 'equipamentos/07.001/garantias/contrato_garantia_07_001_incubadora_neonatal.pdf', '2022-01-20', '2025-01-20', 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '01.001' LIMIT 1), 'contrato_manutencao', 'Contrato de Manutencao - Ventilador Pulmonar', 'equipamentos/01.001/manutencoes/contrato_manutencao_01_001_ventilador_pulmonar.pdf', '2024-03-15', NULL, 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '05.001' LIMIT 1), 'contrato_manutencao', 'Contrato de Manutencao - Bomba Infusora Volumetrica', 'equipamentos/05.001/manutencoes/contrato_manutencao_05_001_bomba_infusora_volumetrica.pdf', '2024-03-10', NULL, 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '08.001' LIMIT 1), 'contrato_manutencao', 'Contrato de Manutencao - Autoclave Hospitalar', 'equipamentos/08.001/manutencoes/contrato_manutencao_08_001_autoclave_hospitalar.pdf', '2024-06-12', NULL, 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '01.001' LIMIT 1), 'contrato_calibracao', 'Contrato de Calibracao - Ventilador Pulmonar', 'equipamentos/01.001/calibracoes/contrato_calibracao_01_001_ventilador_pulmonar.pdf', '2024-03-20', '2025-03-20', 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '05.001' LIMIT 1), 'contrato_calibracao', 'Contrato de Calibracao - Bomba Infusora Volumetrica', 'equipamentos/05.001/calibracoes/contrato_calibracao_05_001_bomba_infusora_volumetrica.pdf', '2024-04-05', '2025-04-05', 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '08.001' LIMIT 1), 'contrato_calibracao', 'Contrato de Calibracao - Autoclave Hospitalar', 'equipamentos/08.001/calibracoes/contrato_calibracao_08_001_autoclave_hospitalar.pdf', '2024-06-20', '2025-06-20', 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '01.001' LIMIT 1), 'manual_instrucoes', 'Manual de Instrucoes - Ventilador Pulmonar', 'equipamentos/01.001/manuais/manual_instrucoes_01_001_ventilador_pulmonar.pdf', '2026-06-23', NULL, 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '05.001' LIMIT 1), 'manual_instrucoes', 'Manual de Instrucoes - Bomba Infusora Volumetrica', 'equipamentos/05.001/manuais/manual_instrucoes_05_001_bomba_infusora_volumetrica.pdf', '2026-06-23', NULL, 'Documento simulado gerado para demonstracao academica.', 'admin');
INSERT INTO documentos_equipamentos (id_equipamento, tipo_documento, nome_documento, caminho_ficheiro, data_documento, data_validade, observacoes, atualizado_por) VALUES ((SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '08.001' LIMIT 1), 'manual_instrucoes', 'Manual de Instrucoes - Autoclave Hospitalar', 'equipamentos/08.001/manuais/manual_instrucoes_08_001_autoclave_hospitalar.pdf', '2026-06-23', NULL, 'Documento simulado gerado para demonstracao academica.', 'admin');