INSERT INTO fornecedores (
    nome_empresa,
    tipo_fornecedor,
    nif,
    email,
    telefone,
    website,
    pessoa_contacto,
    telefone_contacto,
    email_contacto,
    morada,
    codigo_postal,
    localidade,
    pais,
    isActive
) VALUES
(
    'Philips Medical Systems Portugal',
    'Fabricante',
    509123456,
    'suporte@philips-medical.pt',
    220000111,
    'https://www.philips.pt',
    'Carlos Almeida',
    912345678,
    'carlos.almeida@philips-medical.pt',
    'Avenida da Boavista 1837',
    '4100-133',
    'Porto',
    'Portugal',
    1
),
(
    'MedSupply Portugal',
    'Comercial',
    514987321,
    'comercial@medsupply.pt',
    221234567,
    'https://www.medsupply.pt',
    'Ana Martins',
    913456789,
    'ana.martins@medsupply.pt',
    'Rua do Campo Grande 28',
    '1700-093',
    'Lisboa',
    'Portugal',
    1
),
(
    'Biomedical Solutions',
    'Manutenção',
    507654789,
    'tecnica@biomedicalsolutions.pt',
    222456789,
    'https://www.biomedicalsolutions.pt',
    'Rui Ferreira',
    914567890,
    'rui.ferreira@biomedicalsolutions.pt',
    'Rua Engenheiro Frederico Ulrich 2650',
    '4470-605',
    'Maia',
    'Portugal',
    1
),
(
    'Drager Portugal',
    'Fabricante',
    501234987,
    'assistencia@drager.pt',
    218765432,
    'https://www.draeger.com',
    'Marta Costa',
    915678901,
    'marta.costa@drager.pt',
    'Lagoas Park, Edificio 5',
    '2740-245',
    'Oeiras',
    'Portugal',
    1
),
(
    'CalibraMed',
    'Manutenção',
    515321987,
    'geral@calibramed.pt',
    223987654,
    'https://www.calibramed.pt',
    'João Pereira',
    916789012,
    'joao.pereira@calibramed.pt',
    'Parque Tecnologico de Braga',
    '4705-319',
    'Braga',
    'Portugal',
    1
),
(
    'HospitalTech Equipamentos',
    'Comercial',
    508456123,
    'vendas@hospitaltech.pt',
    239123456,
    'https://www.hospitaltech.pt',
    'Sofia Ribeiro',
    917890123,
    'sofia.ribeiro@hospitaltech.pt',
    'Rua Pedro Nunes 303',
    '3030-199',
    'Coimbra',
    'Portugal',
    1
);

INSERT INTO localizacoes (
    codigo,
    departamento_nome,
    departamento_sigla,
    edificio,
    piso,
    sala,
    tipo_espaco,
    estado,
    capacidade_equipamentos,
    permite_equipamentos_criticos,
    observacoes,
    isActive
) VALUES
('UCI-P2-S201', 'Unidade de Cuidados Intensivos', 'UCI', 'Edifício A', '2', '201', 'UCI', 'Ativa', 12, 1, 'Sala destinada a cuidados intensivos com equipamentos críticos.', 1),
('UCI-P2-S202', 'Unidade de Cuidados Intensivos', 'UCI', 'Edifício A', '2', '202', 'UCI', 'Ativa', 10, 1, 'Sala com monitorização contínua de doentes críticos.', 1),
('UCI-P2-S203', 'Unidade de Cuidados Intensivos', 'UCI', 'Edifício A', '2', '203', 'UCI', 'Em manutenção', 8, 1, 'Espaço temporariamente em manutenção técnica.', 1),

('URG-P0-S001', 'Urgência', 'URG', 'Edifício B', '0', '001', 'Urgência', 'Ativa', 15, 1, 'Sala principal de atendimento urgente.', 1),
('URG-P0-S002', 'Urgência', 'URG', 'Edifício B', '0', '002', 'Urgência', 'Ativa', 8, 1, 'Sala de observação rápida.', 1),
('URG-P0-S003', 'Urgência', 'URG', 'Edifício B', '0', '003', 'Triagem', 'Ativa', 5, 0, 'Área destinada à triagem inicial dos utentes.', 1),

('BO-P1-S101', 'Bloco Operatório', 'BO', 'Edifício C', '1', '101', 'Bloco Operatório', 'Ativa', 7, 1, 'Sala operatória equipada para cirurgia geral.', 1),
('BO-P1-S102', 'Bloco Operatório', 'BO', 'Edifício C', '1', '102', 'Bloco Operatório', 'Ativa', 7, 1, 'Sala operatória com suporte para equipamentos críticos.', 1),
('BO-P1-S103', 'Bloco Operatório', 'BO', 'Edifício C', '1', '103', 'Bloco Operatório', 'Indisponível', 6, 1, 'Sala temporariamente indisponível para intervenção técnica.', 1),

('RAD-P0-S010', 'Radiologia', 'RAD', 'Edifício A', '0', '010', 'Radiologia', 'Ativa', 4, 0, 'Sala destinada a exames de imagem.', 1),
('RAD-P0-S011', 'Radiologia', 'RAD', 'Edifício A', '0', '011', 'Radiologia', 'Ativa', 3, 0, 'Sala com equipamento de diagnóstico por imagem.', 1),
('RAD-P0-S012', 'Radiologia', 'RAD', 'Edifício A', '0', '012', 'Radiologia', 'Em manutenção', 2, 0, 'Sala em manutenção preventiva.', 1),

('LAB-P1-S105', 'Laboratório Clínico', 'LAB', 'Edifício D', '1', '105', 'Laboratório', 'Ativa', 10, 0, 'Laboratório destinado ao processamento de amostras clínicas.', 1),
('LAB-P1-S106', 'Laboratório Clínico', 'LAB', 'Edifício D', '1', '106', 'Laboratório', 'Ativa', 8, 0, 'Sala de apoio técnico laboratorial.', 1),
('LAB-P1-S107', 'Laboratório Clínico', 'LAB', 'Edifício D', '1', '107', 'Laboratório', 'Ativa', 6, 0, 'Espaço reservado para equipamentos laboratoriais.', 1),

('CARD-P3-S301', 'Cardiologia', 'CARD', 'Edifício A', '3', '301', 'Consulta Externa', 'Ativa', 5, 0, 'Sala de consulta de cardiologia.', 1),
('CARD-P3-S302', 'Cardiologia', 'CARD', 'Edifício A', '3', '302', 'Consulta Externa', 'Ativa', 5, 0, 'Sala destinada a avaliação cardiológica.', 1),
('CARD-P3-S303', 'Cardiologia', 'CARD', 'Edifício A', '3', '303', 'Sala de Exames', 'Ativa', 6, 0, 'Sala equipada para exames complementares de cardiologia.', 1),

('PED-P2-S210', 'Pediatria', 'PED', 'Edifício B', '2', '210', 'Consulta Externa', 'Ativa', 6, 0, 'Sala de consulta pediátrica.', 1),
('PED-P2-S211', 'Pediatria', 'PED', 'Edifício B', '2', '211', 'Consulta Externa', 'Ativa', 6, 0, 'Sala adaptada ao atendimento pediátrico.', 1),
('PED-P2-S212', 'Pediatria', 'PED', 'Edifício B', '2', '212', 'Sala de Tratamentos', 'Ativa', 7, 0, 'Sala para pequenos procedimentos pediátricos.', 1),

('NEO-P2-S220', 'Neonatologia', 'NEO', 'Edifício B', '2', '220', 'Neonatologia', 'Ativa', 10, 1, 'Sala com suporte para cuidados neonatais.', 1),
('NEO-P2-S221', 'Neonatologia', 'NEO', 'Edifício B', '2', '221', 'Neonatologia', 'Ativa', 8, 1, 'Sala destinada a recém-nascidos com necessidade de monitorização.', 1),

('MI-P4-S401', 'Medicina Interna', 'MI', 'Edifício A', '4', '401', 'Enfermaria', 'Ativa', 12, 0, 'Sala/enfermaria de medicina interna.', 1),
('MI-P4-S402', 'Medicina Interna', 'MI', 'Edifício A', '4', '402', 'Enfermaria', 'Ativa', 12, 0, 'Espaço de internamento de medicina interna.', 1),

('CE-P-1-S001', 'Central de Esterilização', 'CE', 'Edifício Técnico', '-1', '001', 'Esterilização', 'Ativa', 9, 0, 'Área técnica dedicada à esterilização de material.', 1),
('CE-P-1-S002', 'Central de Esterilização', 'CE', 'Edifício Técnico', '-1', '002', 'Esterilização', 'Ativa', 7, 0, 'Sala de apoio ao processamento de material esterilizado.', 1),

('ARM-P-1-S010', 'Armazém Técnico', 'ARM', 'Edifício Técnico', '-1', '010', 'Armazém Técnico', 'Ativa', 20, 0, 'Armazém para equipamentos e acessórios técnicos.', 1),
('ARM-P-1-S011', 'Armazém Técnico', 'ARM', 'Edifício Técnico', '-1', '011', 'Armazém Técnico', 'Ativa', 18, 0, 'Espaço de armazenamento de consumíveis e peças.', 1),

('MN-P1-S115', 'Medicina Nuclear', 'MN', 'Edifício D', '1', '115', 'Sala de Exames', 'Ativa', 4, 0, 'Sala destinada a exames de medicina nuclear.', 1);

-- Inserts adicionais para MEDICORE
-- Executar depois dos INSERTS.sql que já tens para fornecedores e localizações.

-- 1) Famílias de equipamentos
INSERT IGNORE INTO familias_equipamento (codigo_familia, nome, descricao, isActive) VALUES
('01', 'Suporte de vida', 'Equipamentos críticos de suporte ventilatório, reanimação e emergência.', 1),
('02', 'Diagnóstico por imagem', 'Equipamentos usados na aquisição e apoio ao diagnóstico por imagem.', 1),
('03', 'Laboratório clínico', 'Equipamentos laboratoriais para processamento, análise e conservação de amostras.', 1),
('04', 'Monitores de sinais vitais', 'Monitores multiparamétricos e sistemas de monitorização clínica.', 1),
('05', 'Terapêutica e administração', 'Equipamentos destinados à administração controlada de terapêuticas.', 1),
('06', 'Cardiologia', 'Equipamentos de avaliação, diagnóstico e monitorização cardiológica.', 1),
('07', 'Neonatologia e pediatria', 'Equipamentos de apoio clínico a recém-nascidos e doentes pediátricos.', 1),
('08', 'Esterilização', 'Equipamentos técnicos associados à esterilização e reprocessamento de material.', 1),
('09', 'Mobilidade e apoio clínico', 'Equipamentos de apoio à mobilidade, transporte e suporte ao ato clínico.', 1),
('10', 'Informática médica e apoio técnico', 'Equipamentos de apoio digital, rastreabilidade e continuidade operacional.', 1);

INSERT INTO fornecedores (
    nome_empresa,
    tipo_fornecedor,
    nif,
    email,
    telefone,
    website,
    pessoa_contacto,
    telefone_contacto,
    email_contacto,
    morada,
    codigo_postal,
    localidade,
    pais,
    observacoes
) VALUES
(
    'CalibraMed Portugal',
    'Calibração',
    509111222,
    'geral@calibramed.pt',
    210111222,
    'https://www.calibramed.pt',
    'João Martins',
    910111222,
    'joao.martins@calibramed.pt',
    'Rua da Metrologia, 25',
    '1000-250',
    'Lisboa',
    'Portugal',
    'Fornecedor especializado em calibração de equipamentos médicos.'
),
(
    'TecnoCalibra Saúde',
    'Calibração',
    509333444,
    'geral@tecnocalibra.pt',
    220333444,
    'https://www.tecnocalibra.pt',
    'Ana Ribeiro',
    930333444,
    'ana.ribeiro@tecnocalibra.pt',
    'Avenida dos Ensaios Técnicos, 14',
    '4200-140',
    'Porto',
    'Portugal',
    'Empresa responsável por calibrações e ensaios técnicos.'
);

INSERT INTO equipamentos (
    id_familia_equipamento,
    numero_sequencial,
    codigo_equipamento,
    designacao,
    modelo,
    numero_serie,
    tipo_entrada,
    valor_aquisicao,
    id_localizacao,
    estado,
    criticidade,
    periodicidade_manutencao,
    periodicidade_calibracao,
    data_fabrico,
    data_aquisicao,
    data_instalacao,
    responsavel_equipamento,
    observacoes,
    atualizado_por
) VALUES
(
    (SELECT id_familia_equipamento FROM familias_equipamento WHERE codigo_familia = '01' LIMIT 1),
    1,
    '01.001',
    'Ventilador Pulmonar',
    'Evita V600',
    'SN-VENT-001',
    'compra',
    18500.00,
    (SELECT id_localizacao FROM localizacoes WHERE codigo = 'UCI-P2-S201' LIMIT 1),
    'ativo',
    'critica',
    'semestral',
    'anual',
    '2022-01-10',
    '2022-03-01',
    '2022-03-15',
    'Eng. Gonçalo',
    'Equipamento crítico de suporte ventilatório utilizado em cuidados intensivos.',
    'admin'
),
(
    (SELECT id_familia_equipamento FROM familias_equipamento WHERE codigo_familia = '01' LIMIT 1),
    2,
    '01.002',
    'Desfibrilhador Externo',
    'HeartStart XL',
    'SN-DESF-002',
    'compra',
    7200.00,
    (SELECT id_localizacao FROM localizacoes WHERE codigo = 'URG-P0-S001' LIMIT 1),
    'ativo',
    'critica',
    'semestral',
    'anual',
    '2021-05-20',
    '2021-07-10',
    '2021-07-20',
    'Eng. Gonçalo',
    'Equipamento de emergência para suporte avançado de vida.',
    'admin'
),
(
    (SELECT id_familia_equipamento FROM familias_equipamento WHERE codigo_familia = '02' LIMIT 1),
    1,
    '02.001',
    'Ecógrafo Portátil',
    'ClearVue 550',
    'SN-ECO-001',
    'compra',
    32000.00,
    (SELECT id_localizacao FROM localizacoes WHERE codigo = 'RAD-P0-S010' LIMIT 1),
    'ativo',
    'alta',
    'anual',
    'anual',
    '2021-06-12',
    '2021-08-20',
    '2021-09-01',
    'Eng. Gonçalo',
    'Equipamento usado em exames de diagnóstico por imagem.',
    'admin'
),
(
    (SELECT id_familia_equipamento FROM familias_equipamento WHERE codigo_familia = '03' LIMIT 1),
    1,
    '03.001',
    'Centrífuga Laboratorial',
    'LabSpin 3000',
    'SN-CENT-001',
    'compra',
    4500.00,
    (SELECT id_localizacao FROM localizacoes WHERE codigo = 'LAB-P1-S105' LIMIT 1),
    'ativo',
    'media',
    'anual',
    'anual',
    '2023-02-18',
    '2023-04-10',
    '2023-04-20',
    'Eng. Gonçalo',
    'Equipamento laboratorial para processamento de amostras clínicas.',
    'admin'
),
(
    (SELECT id_familia_equipamento FROM familias_equipamento WHERE codigo_familia = '04' LIMIT 1),
    1,
    '04.001',
    'Monitor Multiparamétrico',
    'IntelliVue MX450',
    'SN-MON-001',
    'compra',
    6200.00,
    (SELECT id_localizacao FROM localizacoes WHERE codigo = 'UCI-P2-S202' LIMIT 1),
    'ativo',
    'alta',
    'anual',
    'bienal',
    '2022-06-01',
    '2022-08-10',
    '2022-08-20',
    'Eng. Gonçalo',
    'Monitorização contínua de sinais vitais em contexto hospitalar.',
    'admin'
),
(
    (SELECT id_familia_equipamento FROM familias_equipamento WHERE codigo_familia = '05' LIMIT 1),
    1,
    '05.001',
    'Bomba Infusora Volumétrica',
    'Infusomat Space',
    'SN-INF-001',
    'compra',
    2450.00,
    (SELECT id_localizacao FROM localizacoes WHERE codigo = 'MI-P4-S401' LIMIT 1),
    'ativo',
    'critica',
    'anual',
    'anual',
    '2023-01-15',
    '2023-03-01',
    '2023-03-10',
    'Eng. Gonçalo',
    'Equipamento destinado à administração controlada de terapêutica intravenosa.',
    'admin'
),
(
    (SELECT id_familia_equipamento FROM familias_equipamento WHERE codigo_familia = '06' LIMIT 1),
    1,
    '06.001',
    'Eletrocardiógrafo',
    'PageWriter TC30',
    'SN-ECG-001',
    'compra',
    3800.00,
    (SELECT id_localizacao FROM localizacoes WHERE codigo = 'CARD-P3-S303' LIMIT 1),
    'ativo',
    'alta',
    'anual',
    'bienal',
    '2020-09-05',
    '2020-10-15',
    '2020-10-25',
    'Eng. Gonçalo',
    'Equipamento de apoio ao diagnóstico cardiológico.',
    'admin'
),
(
    (SELECT id_familia_equipamento FROM familias_equipamento WHERE codigo_familia = '07' LIMIT 1),
    1,
    '07.001',
    'Incubadora Neonatal',
    'Isolette 8000',
    'SN-INC-001',
    'compra',
    14500.00,
    (SELECT id_localizacao FROM localizacoes WHERE codigo = 'NEO-P2-S220' LIMIT 1),
    'ativo',
    'critica',
    'semestral',
    'anual',
    '2021-11-20',
    '2022-01-10',
    '2022-01-20',
    'Eng. Gonçalo',
    'Equipamento de suporte clínico neonatal.',
    'admin'
),
(
    (SELECT id_familia_equipamento FROM familias_equipamento WHERE codigo_familia = '08' LIMIT 1),
    1,
    '08.001',
    'Autoclave Hospitalar',
    'Sterilizer 1000',
    'SN-AUT-001',
    'compra',
    21000.00,
    (SELECT id_localizacao FROM localizacoes WHERE codigo = 'CE-P-1-S001' LIMIT 1),
    'em_manutencao',
    'alta',
    'semestral',
    'anual',
    '2019-04-10',
    '2019-06-01',
    '2019-06-15',
    'Eng. Gonçalo',
    'Equipamento de esterilização e reprocessamento de material clínico.',
    'admin'
),
(
    (SELECT id_familia_equipamento FROM familias_equipamento WHERE codigo_familia = '09' LIMIT 1),
    1,
    '09.001',
    'Cama Hospitalar Elétrica',
    'Eleganza Smart',
    'SN-CAMA-001',
    'compra',
    2950.00,
    (SELECT id_localizacao FROM localizacoes WHERE codigo = 'MI-P4-S402' LIMIT 1),
    'ativo',
    'media',
    'anual',
    NULL,
    '2022-12-01',
    '2023-01-10',
    '2023-01-20',
    'Eng. Gonçalo',
    'Equipamento de apoio clínico e mobilidade do doente.',
    'admin'
);

INSERT INTO equipamentos_fornecedores (
    id_equipamento,
    id_fornecedor_fabricante,
    id_fornecedor_comercial,
    id_fornecedor_garantia,
    data_inicio_garantia,
    data_fim_garantia,
    observacoes,
    atualizado_por
) VALUES
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '01.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Drager Portugal' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'MedSupply Portugal' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Drager Portugal' LIMIT 1),
    '2022-03-15',
    '2025-03-15',
    'Garantia assegurada pelo fabricante.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '01.002' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Philips Medical Systems Portugal' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'HospitalTech Equipamentos' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'HospitalTech Equipamentos' LIMIT 1),
    '2021-07-20',
    '2024-07-20',
    'Garantia assegurada pelo fornecedor comercial.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '02.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Philips Medical Systems Portugal' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'MedSupply Portugal' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Philips Medical Systems Portugal' LIMIT 1),
    '2021-09-01',
    '2024-09-01',
    'Garantia assegurada pelo fabricante.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '03.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Biomedical Solutions' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'MedSupply Portugal' LIMIT 1),
    NULL,
    NULL,
    NULL,
    'Equipamento sem fornecedor de garantia associado.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '04.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Philips Medical Systems Portugal' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'HospitalTech Equipamentos' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'HospitalTech Equipamentos' LIMIT 1),
    '2022-08-20',
    '2025-08-20',
    'Garantia associada ao fornecedor comercial.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '05.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Biomedical Solutions' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'MedSupply Portugal' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'MedSupply Portugal' LIMIT 1),
    '2023-03-10',
    '2026-03-10',
    'Garantia válida por três anos.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '06.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Philips Medical Systems Portugal' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'HospitalTech Equipamentos' LIMIT 1),
    NULL,
    NULL,
    NULL,
    'Sem garantia ativa registada.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '07.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Drager Portugal' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'HospitalTech Equipamentos' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Drager Portugal' LIMIT 1),
    '2022-01-20',
    '2025-01-20',
    'Garantia assegurada pelo fabricante.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '08.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Biomedical Solutions' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'MedSupply Portugal' LIMIT 1),
    NULL,
    NULL,
    NULL,
    'Garantia expirada ou não aplicável.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '09.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'HospitalTech Equipamentos' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'HospitalTech Equipamentos' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'HospitalTech Equipamentos' LIMIT 1),
    '2023-01-20',
    '2025-01-20',
    'Garantia associada ao fornecedor comercial.',
    'admin'
);

INSERT INTO manutencoes_equipamento (
    id_equipamento,
    tipo_manutencao,
    id_fornecedor_responsavel,
    tecnico_interno,
    data_manutencao,
    proxima_manutencao,
    descricao_procedimento,
    resultado,
    coberta_por_garantia,
    custo,
    observacoes,
    atualizado_por
) VALUES
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '01.001' LIMIT 1),
    'preventiva',
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Drager Portugal' LIMIT 1),
    NULL,
    '2024-03-15',
    '2024-09-15',
    'Inspeção geral, teste funcional, verificação de alarmes e limpeza técnica.',
    'realizada',
    1,
    0.00,
    'Manutenção realizada durante o período de garantia.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '01.002' LIMIT 1),
    'preventiva',
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Biomedical Solutions' LIMIT 1),
    NULL,
    '2024-07-20',
    '2025-01-20',
    'Teste de descarga, inspeção dos elétrodos, verificação da bateria e alarmes.',
    'realizada',
    0,
    140.00,
    'Manutenção preventiva realizada por fornecedor técnico.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '02.001' LIMIT 1),
    'preventiva',
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Biomedical Solutions' LIMIT 1),
    NULL,
    '2024-09-01',
    '2025-09-01',
    'Verificação funcional, inspeção dos transdutores e limpeza técnica.',
    'realizada_com_observacoes',
    0,
    220.00,
    'Recomendada substituição futura de cabo de sonda.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '03.001' LIMIT 1),
    'preventiva',
    NULL,
    'Técnico Interno - Engenharia Clínica',
    '2024-04-20',
    '2025-04-20',
    'Limpeza, inspeção visual, verificação de rotação e teste funcional.',
    'realizada',
    0,
    NULL,
    'Intervenção interna sem necessidade de fornecedor externo.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '04.001' LIMIT 1),
    'corretiva',
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Biomedical Solutions' LIMIT 1),
    NULL,
    '2024-11-10',
    NULL,
    'Substituição de cabo ECG danificado e teste funcional posterior.',
    'realizada',
    0,
    95.00,
    'Equipamento voltou ao serviço após intervenção.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '05.001' LIMIT 1),
    'preventiva',
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'MedSupply Portugal' LIMIT 1),
    NULL,
    '2024-03-10',
    '2025-03-10',
    'Teste de alarmes, inspeção mecânica e verificação do funcionamento geral.',
    'realizada',
    1,
    0.00,
    'Manutenção coberta pela garantia.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '06.001' LIMIT 1),
    'preventiva',
    NULL,
    'Técnico Interno - Engenharia Clínica',
    '2024-10-25',
    '2025-10-25',
    'Inspeção visual, teste de aquisição de sinal e verificação de acessórios.',
    'realizada',
    0,
    NULL,
    'Sem anomalias detetadas.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '07.001' LIMIT 1),
    'preventiva',
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'Drager Portugal' LIMIT 1),
    NULL,
    '2024-01-20',
    '2024-07-20',
    'Verificação de temperatura, alarmes, sensores e integridade física.',
    'realizada',
    1,
    0.00,
    'Intervenção realizada no âmbito da garantia.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '08.001' LIMIT 1),
    'corretiva',
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'CalibraMed' LIMIT 1),
    NULL,
    '2024-06-12',
    NULL,
    'Correção de falha no ciclo de esterilização e teste de funcionamento.',
    'realizada_com_observacoes',
    0,
    350.00,
    'Necessária nova avaliação no próximo ciclo preventivo.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '09.001' LIMIT 1),
    'preventiva',
    NULL,
    'Técnico Interno - Engenharia Clínica',
    '2024-01-20',
    '2025-01-20',
    'Verificação de comandos elétricos, travões e estrutura mecânica.',
    'realizada',
    0,
    NULL,
    'Equipamento funcional.',
    'admin'
);

INSERT INTO calibracoes_equipamento (
    id_equipamento,
    id_fornecedor_responsavel,
    tecnico_interno,
    data_calibracao,
    proxima_calibracao,
    numero_certificado,
    resultado,
    procedimento,
    coberta_por_garantia,
    custo,
    observacoes,
    atualizado_por
) VALUES
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '01.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'CalibraMed Portugal' LIMIT 1),
    NULL,
    '2024-03-20',
    '2025-03-20',
    'CERT-01-001-2024',
    'aprovado',
    'Verificação de parâmetros ventilatórios e alarmes associados.',
    0,
    180.00,
    'Equipamento aprovado para utilização clínica.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '01.002' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'TecnoCalibra Saúde' LIMIT 1),
    NULL,
    '2024-07-25',
    '2025-07-25',
    'CERT-01-002-2024',
    'aprovado',
    'Verificação dos parâmetros de energia, descarga e segurança funcional.',
    0,
    150.00,
    'Certificado emitido sem restrições.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '02.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'TecnoCalibra Saúde' LIMIT 1),
    NULL,
    '2024-09-05',
    '2025-09-05',
    'CERT-02-001-2024',
    'aprovado',
    'Verificação funcional e calibração dos parâmetros aplicáveis.',
    0,
    250.00,
    'Calibração anual concluída.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '03.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'CalibraMed Portugal' LIMIT 1),
    NULL,
    '2024-04-25',
    '2025-04-25',
    'CERT-03-001-2024',
    'aprovado',
    'Calibração de velocidade de rotação e temporização.',
    0,
    90.00,
    'Equipamento conforme.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '04.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'TecnoCalibra Saúde' LIMIT 1),
    NULL,
    '2024-09-01',
    '2026-09-01',
    'CERT-04-001-2024',
    'aprovado',
    'Verificação de parâmetros de monitorização e módulos disponíveis.',
    0,
    130.00,
    'Validade bienal.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '05.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'CalibraMed Portugal' LIMIT 1),
    NULL,
    '2024-04-05',
    '2025-04-05',
    'CERT-05-001-2024',
    'aprovado',
    'Ensaio metrológico de caudal e volume administrado.',
    0,
    85.00,
    'Equipamento aprovado.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '06.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'TecnoCalibra Saúde' LIMIT 1),
    NULL,
    '2024-10-30',
    '2026-10-30',
    'CERT-06-001-2024',
    'aprovado',
    'Verificação dos parâmetros elétricos e funcionais do ECG.',
    0,
    110.00,
    'Equipamento conforme.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '07.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'CalibraMed Portugal' LIMIT 1),
    NULL,
    '2024-02-01',
    '2025-02-01',
    'CERT-07-001-2024',
    'aprovado_com_restricoes',
    'Verificação de temperatura, humidade e alarmes.',
    1,
    0.00,
    'Aprovado com recomendação de vigilância do sensor de humidade.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '08.001' LIMIT 1),
    (SELECT id_fornecedor FROM fornecedores WHERE nome_empresa = 'TecnoCalibra Saúde' LIMIT 1),
    NULL,
    '2024-06-20',
    '2025-06-20',
    'CERT-08-001-2024',
    'aprovado',
    'Verificação de temperatura, pressão e parâmetros do ciclo.',
    0,
    200.00,
    'Autoclave aprovada após correção.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '09.001' LIMIT 1),
    NULL,
    'Técnico Interno - Engenharia Clínica',
    '2024-01-25',
    NULL,
    'VER-09-001-2024',
    'aprovado',
    'Verificação funcional interna dos comandos e segurança elétrica básica.',
    0,
    NULL,
    'Registo interno sem certificado externo.',
    'admin'
);

INSERT INTO documentos_equipamentos (
    id_equipamento,
    id_manutencao,
    id_calibracao,
    id_equipamento_fornecedor,
    tipo_documento,
    nome_documento,
    caminho_ficheiro,
    data_documento,
    data_validade,
    observacoes,
    atualizado_por
) VALUES
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '01.001' LIMIT 1),
    NULL,
    NULL,
    NULL,
    'manual_instrucoes',
    'Manual de Instruções - Ventilador Pulmonar',
    'equipamentos/01.001/manual_instrucoes.pdf',
    '2022-03-15',
    NULL,
    'Manual técnico do ventilador pulmonar.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '01.002' LIMIT 1),
    NULL,
    NULL,
    NULL,
    'manual_instrucoes',
    'Manual de Instruções - Desfibrilhador Externo',
    'equipamentos/01.002/manual_instrucoes.pdf',
    '2021-07-20',
    NULL,
    'Manual de operação do desfibrilhador.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '02.001' LIMIT 1),
    NULL,
    NULL,
    NULL,
    'datasheet',
    'Datasheet - Ecógrafo Portátil',
    'equipamentos/02.001/datasheet.pdf',
    '2021-09-01',
    NULL,
    'Ficha técnica do ecógrafo portátil.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '04.001' LIMIT 1),
    NULL,
    NULL,
    NULL,
    'manual_instrucoes',
    'Manual de Instruções - Monitor Multiparamétrico',
    'equipamentos/04.001/manual_instrucoes.pdf',
    '2022-08-20',
    NULL,
    'Manual de utilização do monitor multiparamétrico.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '05.001' LIMIT 1),
    NULL,
    NULL,
    NULL,
    'datasheet',
    'Datasheet - Bomba Infusora Volumétrica',
    'equipamentos/05.001/datasheet.pdf',
    '2023-03-10',
    NULL,
    'Ficha técnica da bomba infusora.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '05.001' LIMIT 1),
    NULL,
    (SELECT id_calibracao FROM calibracoes_equipamento WHERE numero_certificado = 'CERT-05-001-2024' LIMIT 1),
    NULL,
    'certificado_calibracao',
    'Certificado de Calibração - Bomba Infusora - 2024',
    'equipamentos/05.001/calibracoes/certificado_2024.pdf',
    '2024-04-05',
    '2025-04-05',
    'Certificado associado à calibração anual.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '01.001' LIMIT 1),
    NULL,
    (SELECT id_calibracao FROM calibracoes_equipamento WHERE numero_certificado = 'CERT-01-001-2024' LIMIT 1),
    NULL,
    'certificado_calibracao',
    'Certificado de Calibração - Ventilador Pulmonar - 2024',
    'equipamentos/01.001/calibracoes/certificado_2024.pdf',
    '2024-03-20',
    '2025-03-20',
    'Certificado de calibração do ventilador.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '08.001' LIMIT 1),
    (SELECT id_manutencao FROM manutencoes_equipamento 
     WHERE id_equipamento = (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '08.001' LIMIT 1)
       AND data_manutencao = '2024-06-12'
     LIMIT 1),
    NULL,
    NULL,
    'relatorio_manutencao',
    'Relatório de Manutenção Corretiva - Autoclave',
    'equipamentos/08.001/manutencoes/relatorio_corretiva_2024.pdf',
    '2024-06-12',
    NULL,
    'Relatório técnico da intervenção corretiva.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '07.001' LIMIT 1),
    NULL,
    NULL,
    (SELECT id_equipamento_fornecedor FROM equipamentos_fornecedores 
     WHERE id_equipamento = (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '07.001' LIMIT 1)
     LIMIT 1),
    'garantia',
    'Documento de Garantia - Incubadora Neonatal',
    'equipamentos/07.001/garantia/documento_garantia.pdf',
    '2022-01-20',
    '2025-01-20',
    'Documento comprovativo da garantia do equipamento.',
    'admin'
),
(
    (SELECT id_equipamento FROM equipamentos WHERE codigo_equipamento = '03.001' LIMIT 1),
    NULL,
    NULL,
    NULL,
    'declaracao_conformidade',
    'Declaração de Conformidade - Centrífuga Laboratorial',
    'equipamentos/03.001/declaracao_conformidade.pdf',
    '2023-04-20',
    NULL,
    'Declaração de conformidade do equipamento laboratorial.',
    'admin'
);



